name: ClanPro
author: echno889
description: A Plugin For Easily Managing Clans
version: 1.0.0
main: ClanPro\ClanMain
api: [3.0.0]
softdepend: ["AntiSpamPro"]
extensions: [sqlite3]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
